fullnameOverride: auth-db

auth:
  rootPassword: "auth-root-pass"
  database: auth_db
  username: auth_user
  password: "auth-pass"

persistence:
  enabled: true
  size: 5Gi
  storageClass: "standard" # or your Minikube default

configuration: |
  [mysqld]
  max_connections = 200

initdbScripts:
  create-monitoring-user.sql: |
    CREATE USER 'monitor_user'@'%' IDENTIFIED BY 'monitor_pass';
    GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'monitor_user'@'%';

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus

service:
  type: ClusterIP
