persistence:
  enabled: true
  size: 5Gi

configuration: |
  [mariadb]
  max_connections = 500

mariadb:
  databases:
    - name: auth_db
      user: auth_user
      password: auth_pass

auth:
  existingSecret: mariadb-root-password

metrics:
  enabled: true

service:
  type: NodePort

initdbScripts:
  create-monitoring-user.sql: |
    CREATE USER 'monitor'@'%' IDENTIFIED BY 'monitor_password';
    GRANT SELECT ON *.* TO 'monitor'@'%';
    FLUSH PRIVILEGES;
