persistence:
  enabled: true
  size: 5Gi

configuration: |
  [mariadb]
  max_connections = 500

mariadb:
  databases:
    - name: auth_db
      user: auth_user
      password: auth_pass

auth:
  existingSecret: mariadb-root-password

metrics:
  enabled: true

service:
  type: NodePort

initdbScripts:
  create-monitoring-user.sql: |
    CREATE USER 'monitor'@'%' IDENTIFIED BY 'monitor_password';
    GRANT ALL PRIVILEGES ON auth_db.* TO 'auth_user'@'%' IDENTIFIED BY 'auth_pass';
    FLUSH PRIVILEGES;
  create-database.sql: |
    CREATE DATABASE IF NOT EXISTS auth_db;
    CREATE USER IF NOT EXISTS 'auth_user'@'%' IDENTIFIED BY 'auth_pass';
    GRANT ALL PRIVILEGES ON auth_db.* TO 'auth_user'@'%';
    FLUSH PRIVILEGES;
