auth:
  rootPassword: "root_pass"
  username: "auth_user"
  password: "auth_pass"
  database: "auth_db"

image:
  registry: docker.io
  repository: bitnami/mariadb
  tag: 11.3.2-debian-12-r1
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 8Gi
  storageClass: "standard"

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

architecture: standalone

metrics:
  enabled: true
  exporter:
    image:
      tag: 0.15.0-debian-12-r1

primary:
  config:
    max_connections: 50
  extraEnvVars:
    - name: MARIADB_MONITOR_USER
      value: "monitor_auth"
    - name: MARIADB_MONITOR_PASSWORD
      value: "monitor_pass"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
    prometheus.io/path: "/metrics"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
