global:
  postgresql:
    auth:
      username: "inventory_user"
      password: "inventory_pass"
      database: "inventory_db"
      existingSecret: ""
      secretKeys:
        userPasswordKey: "inventory_pass"
    servicePort: 5432

architecture: standalone

persistence:
  enabled: true
  size: 8Gi
  storageClass: "standard"

primary:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  extendedConfiguration: |
    max_connections = 50
  extraEnvVars:
    - name: POSTGRES_USER_MONITORING
      value: "monitor_inventory"
    - name: POSTGRES_PASSWORD_MONITORING
      value: "monitoring_pass"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    prometheus.io/path: "/metrics"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
