# kafka-values.yaml (for Strimzi 0.39–0.45)
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  # --- Kafka (with ZooKeeper) ---
  kafka:
    version: 3.7.0 # Supported in older Strimzi
    replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: "1000m"
      limits:
        memory: 3Gi
        cpu: "2000m"
    # Probes (supported since Strimzi 0.22+)
    readinessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    # ❌ startupProbe NOT supported in old Strimzi → omit it
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral

  # --- ZooKeeper (required in old Strimzi) ---
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: "200m"
      limits:
        memory: 1Gi
        cpu: "500m"
    storage:
      type: ephemeral

  # --- Entity Operator ---
  entityOperator:
    topicOperator: {}
    userOperator: {}
