resources:
  requests:
    cpu: "600m" # 60% of 1 CPU; adjust based on your Minikube setup
    memory: "600Mi"
  limits:
    cpu: "1000m" # Max CPU limit
    memory: "1Gi"

livenessProbe:
  tcpSocket:
    port: 9092
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 6

readinessProbe:
  tcpSocket:
    port: 9092
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

startupProbe:
  tcpSocket:
    port: 9092
  initialDelaySeconds: 5
  periodSeconds: 15
  failureThreshold: 12

podRestartPolicy: Always # Usually default for statefulsets
