apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
  # This example uses KRaft mode.
  # Ensure your Strimzi Operator version supports it (0.40.0+).
  # See: https://strimzi.io/docs/operators/latest/full/configuring.html#ref-kafka-kraft-mode-str
  kafkaNodePools:
    - name: default
      replicas: 3
      roles:
        - controller
        - broker
      storage:
        type: ephemeral
