# kafka-strimzi.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  # --- Kafka in KRaft mode (no ZooKeeper) ---
  kafka:
    version: 4.1.0 # Must be 4.0.0 or 4.1.0
    replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: "1000m"
      limits:
        memory: 3Gi
        cpu: "2000m"
    # Probes go inside 'template'
    template:
      pod:
        containers:
          - name: kafka
            readinessProbe:
              initialDelaySeconds: 15
              periodSeconds: 10
              timeoutSeconds: 5
            livenessProbe:
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
            # ✅ startupProbe is supported in newer Strimzi
            startupProbe:
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 30

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    storage:
      type: ephemeral

  # --- KRaft requires 'processRoles' and 'controller' config ---
  entityOperator:
    topicOperator: {}
    userOperator: {}
