# values/kafka-values.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.1.0
    replicas: 1
    processRoles:
      - broker
      - controller
    resources:
      requests:
        memory: 2Gi
        cpu: "1000m"
      limits:
        memory: 3Gi
        cpu: "2000m"
    readinessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: controller
        port: 9093
        type: internal
        tls: false
        controller: true
    storage:
      type: jbod
      volumes:
        - id: 0
          type: ephemeral
          size: 10Gi
    config:
      controller.quorum.voters: "0@localhost:9093"
  entityOperator:
    topicOperator: {}
    userOperator: {}
