# kafka-strimzi.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
meta:
  name: my-cluster
  namespace: kafka
spec:
  # --- Kafka Brokers ---
  kafka:
    version: 3.7.0
    replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: "1000m"
      limits:
        memory: 3Gi # ~60% of 6GB Minikube
        cpu: "2000m" # 2 cores out of 4
    readinessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    # Startup probe (critical for slow disk)
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30 # Wait up to 5 minutes

    # Listeners
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    # Storage
    storage:
      type: ephemeral # No persistence (dev only)

  # --- ZooKeeper (required for Kafka < 4.0) ---
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: "200m"
      limits:
        memory: 1Gi
        cpu: "500m"
    storage:
      type: ephemeral

  # --- Entity Operator (manages topics/users) ---
  entityOperator:
    topicOperator: {}
    userOperator: {}
