# kafka-strimzi.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  # --- Kafka in KRaft mode (no ZooKeeper) ---
  kafka:
    version: 4.1.0
    replicas: 1

    # 🔑 Required for KRaft: this node acts as both broker and controller
    processRoles:
      - broker
      - controller

    resources:
      requests:
        memory: 2Gi
        cpu: "1000m"
      limits:
        memory: 3Gi
        cpu: "2000m"

    # ✅ CORRECT WAY: probes are direct children of 'kafka'
    readinessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      # 🔑 Required for KRaft: controller listener
      - name: controller
        port: 9093
        type: internal
        tls: false
        # Only for controller communication
        controller: true

    # 🔑 KRaft storage: must include 'metadata' volume
    storage:
      type: ephemeral
      volumes:
        - id: 0
          type: ephemeral
          size: 10Gi # Adjust as needed

    # Optional: tune KRaft settings
    config:
      # Ensure controller quorum is local
      controller.quorum.voters: "0@localhost:9093"
      # Other Kafka configs...

  # --- Entity Operator (topics/users) ---
  entityOperator:
    topicOperator: {}
    userOperator: {}
