global:
  postgresql:
    auth:
      username: "order_user"
      password: "order_pass"
      database: "order_db"
      existingSecret: ""
      secretKeys:
        userPasswordKey: "order_pass"

image:
  registry: docker.io
  repository: postgres
  tag: 17.6
  pullPolicy: IfNotPresent

architecture: standalone

persistence:
  enabled: true
  size: 8Gi
  storageClass: "standard"

primary:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  extendedConfiguration: |
    max_connections = 50
  env:
    - name: POSTGRES_USER
      value: "order_user"
    - name: POSTGRES_PASSWORD
      value: "order_pass"
    - name: POSTGRES_DB
      value: "order_db"
    - name: POSTGRES_USER_MONITORING
      value: "monitor_order"
    - name: POSTGRES_PASSWORD_MONITORING
      value: "monitor_pass"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    prometheus.io/path: "/metrics"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
