persistence:
  enabled: true
  size: 5Gi

configuration: |
  [mariadb]
  max_connections = 500

mariadb:
  databases:
    - name: order_db
      user: order_user
      password: order_pass

auth:
  existingSecret: mariadb-root-password

metrics:
  enabled: true

service:
  type: NodePort

initdbScripts:
  create-monitoring-user.sql: |
    CREATE USER 'monitor'@'%' IDENTIFIED BY 'monitor_password';
    GRANT ALL PRIVILEGES ON order_db.* TO 'order_user'@'%' IDENTIFIED BY 'order_pass';
    FLUSH PRIVILEGES;
  create-database.sql: |
    CREATE DATABASE IF NOT EXISTS order_db;
    CREATE USER IF NOT EXISTS 'order_user'@'%' IDENTIFIED BY 'order_pass';
    GRANT ALL PRIVILEGES ON order_db.* TO 'order_user'@'%';
    FLUSH PRIVILEGES;
