mode: deployment
config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: "postgres"
            scrape_interval: 15s
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+);(\d+)
                replacement: $1:$2
  processors:
    batch:
  exporters:
    otlp:
      endpoint: "my-signoz-otel-collector.observability.svc.cluster.local:8080"
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [batch]
        exporters: [otlp]
