mode: deployment # or daemonset/statefulset based on your need

config: |
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: "mariadb"
            static_configs:
              - targets: ["auth-db.default.svc.cluster.local:9104"]

  exporters:
    otlp:
      endpoint: "my-release-signoz-otel-collector.platform.svc.cluster.local:4317"
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        exporters: [otlp]
