image:
  repository: otel/opentelemetry-collector-contrib
  # You can specify the version/tag if you want, e.g.
  # tag: "0.59.0"
mode: deployment
# Your existing config block
config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: "mariadb"
            static_configs:
              - targets: ["auth-db-mariadb.default.svc.cluster.local:9104"]
  exporters:
    otlp:
      endpoint: "my-signoz-otel-collector.observability.svc.cluster.local:4317"
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        exporters: [otlp]
