global:
  storageClass: "standard"

# Отключите внешний collector — используем только встроенный
otelCollector:
  enabled: true # ← должен быть true (по умолчанию и так true)
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    exporters:
      clickhouse:
        endpoint: "http://my-signoz-clickhouse:8123"
        username: "default"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [clickhouse]
        metrics:
          receivers: [otlp]
          exporters: [clickhouse]
        logs:
          receivers: [otlp]
          exporters: [clickhouse]
