global:
  storageClass: "standard" # Minikube's default

frontend:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  restartPolicy: Always

queryService:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  restartPolicy: Always

clickhouse:
  enabled: true
  install: true
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

otelCollector:
  enabled: true
  env:
    - name: TENANT_ID
      value: "default"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    exporters:
      # Traces
      clickhousetraces:
        endpoint: "http://my-signoz-clickhouse:8123"
        username: "default"
        timeout: 10s

      # Metrics
      signozclickhousemetrics:
        endpoint: "http://my-signoz-clickhouse:8123"
        username: "default"
        timeout: 10s

      # Logs
      clickhouselogsexporter:
        endpoint: "http://my-signoz-clickhouse:8123"
        username: "default"
        timeout: 10s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [clickhousetraces]
        metrics:
          receivers: [otlp]
          exporters: [signozclickhousemetrics]
        logs:
          receivers: [otlp]
          exporters: [clickhouselogsexporter]
