otelCollector:
  enabled: true
  env:
    - name: TENANT_ID
      value: "default"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    exporters:
      # Traces
      clickhousetraces:
        endpoint: "http://my-signoz-clickhouse:8123"
        username: "default"
        timeout: 10s

      # Metrics
      signozclickhousemetrics:
        endpoint: "http://my-signoz-clickhouse:8123"
        username: "default"
        timeout: 10s

      # Logs
      clickhouselogsexporter:
        endpoint: "http://my-signoz-clickhouse:8123"
        username: "default"
        timeout: 10s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [clickhousetraces]
        metrics:
          receivers: [otlp]
          exporters: [signozclickhousemetrics]
        logs:
          receivers: [otlp]
          exporters: [clickhouselogsexporter]
