# charts/inventory-service/values.yaml
replicaCount: 2

image:
  repository: inventory-service # ← замените на ваш образ
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Целевая нагрузка — 60% CPU → HPA срабатывает при 300m (60% от 500m)
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

env:
  DB_HOST: "inventory-db"
  DB_PORT: "5432"
  DB_USER: "auth_user"
  DB_PASSWORD: "auth_pass"
  DB_NAME: "auth_db"
  REDIS_ADDR: "redis-master:6379"
  JWT_SECRET: "super-secret-jwt-key"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://signoz-otel-collector:4317" # SigNoz OTLP endpoint

# Probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  startup:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 30
